// Re-export actual implementations
export { default as MinigameSelection } from './MinigameSelection'
export { default as GamePlay } from './GamePlay'
export { default as VideoGallery } from './VideoGallery'
export { default as WeeklyRanking } from './WeeklyRanking'
export { default as AdminLogin } from './AdminLogin'
export { default as AdminDashboard } from './AdminDashboard'
export { default as AdminStudents } from './AdminStudents'
export { default as AdminGames } from './AdminGames'
export { default as AdminVocabulary } from './AdminVocabulary'
export { default as AdminVideos } from './AdminVideos'
